# Secret para credenciais do PostgreSQL
# Os valores estão em base64. Para gerar: echo -n 'valor' | base64
# Valores atuais: 
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: postgres123
#   POSTGRES_DB: messagesdb
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  POSTGRES_DB: bWVzc2FnZXNkYg==
---
# Secret para o backend acessar o banco (mesmo namespace do backend)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: app
  labels:
    app: backend
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXMxMjM=
